# Chart Metadata
# Metadata: Defines the chart's name, version, description, and API version.
# Dependencies: Lists other external charts this package depends on.
# Maintainers: Details the authors, maintainers, and home URL of the project.


apiVersion: v2
name: fraud-detection-chart
description: Helm Chart for Fraud Detection Microservice System
type: application
version: 0.1.0
appVersion: "1.0.0"
