# Shared Configurations
# Default Settings: Sets default configuration values for your application (e.g., replica count, image tags, port numbers).
# Customization Target: Serves as the primary place users edit settings when installing or updating the chart.
# Template Inputs: Supplies the variables referenced inside the deployment and service templates.


environment: development

postgres:
  enabled: true
  user: fraud_user
  password: securepassword123   # This secret should not exist here. 
                                # Should be detectable by trufflehog or git leaks.
                                # Delete it, then try secret detection
  dbName: fraud_db
  storageSize: 5Gi

mlService:
  image: local-registry/fraud-ml-api:latest
  replicaCount: 2
  port: 8000
  modelStorageSize: 2Gi

frontend:
  image: local-registry/fraud-frontend:latest
  replicaCount: 1
  port: 8501
