# Configuration Data: Stores non-sensitive configuration settings, 
#     command-line arguments, or config files.
# Pod Injection: Allows applications to read settings via environment variables or
#      mounted volumes without rebuilding images.

apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-training-script
data:
  train_model.py: |-
{{ .Files.Get "scripts/train_model.py" | indent 4 }}